---
- name: Install auditd
  apt:
    name: auditd
    state: present

- name: Enable and start auditd
  service:
    name: auditd
    state: started
    enabled: yes

- name: Deploy sudoers audit rules
  copy:
    src: sudoers-change.rules
    dest: /etc/audit/rules.d/10-sudoers.rules
    mode: '0640'
  notify: Load audit rules
